title: buildnet
logo: docs /assets/62f00bfc-3f09-492e-a197-c6e9c304c807.jpg
description: buildnet revolutunizing b2b and b2c platform in india bridging manufacturers and buyers buildnet 
#show_downloads: true 
theme: jekyll-theme-minimal
